import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JIB 6
 */
public class Fortune_Telling extends javax.swing.JFrame {

    /**
     * Creates new form Fortune_Telling
     */
    public Fortune_Telling() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rdlThursday = new javax.swing.JRadioButton();
        lblPersen = new javax.swing.JLabel();
        rdlFriday = new javax.swing.JRadioButton();
        rdlSunday = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        btnPredict = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rdlMonday = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tarCharacter = new javax.swing.JTextArea();
        rdlTuesday = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tarCharcterlove = new javax.swing.JTextArea();
        rdlSaturday = new javax.swing.JRadioButton();
        btnExit = new javax.swing.JButton();
        rdlWednesday = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fortune Telling ");

        jPanel1.setBackground(new java.awt.Color(255, 51, 102));

        rdlThursday.setBackground(new java.awt.Color(255, 51, 102));
        buttonGroup1.add(rdlThursday);
        rdlThursday.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdlThursday.setForeground(new java.awt.Color(255, 255, 255));
        rdlThursday.setText("วันพฤหัสบดี");
        rdlThursday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdlThursdayActionPerformed(evt);
            }
        });

        lblPersen.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblPersen.setForeground(new java.awt.Color(255, 255, 255));
        lblPersen.setText(" ");

        rdlFriday.setBackground(new java.awt.Color(255, 51, 102));
        buttonGroup1.add(rdlFriday);
        rdlFriday.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdlFriday.setForeground(new java.awt.Color(255, 255, 255));
        rdlFriday.setText("วันศุกร์");
        rdlFriday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdlFridayActionPerformed(evt);
            }
        });

        rdlSunday.setBackground(new java.awt.Color(255, 51, 102));
        buttonGroup1.add(rdlSunday);
        rdlSunday.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdlSunday.setForeground(new java.awt.Color(255, 255, 255));
        rdlSunday.setText("วันอาทิตย์");
        rdlSunday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdlSundayActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ระดับความคลั่งรัก");

        btnPredict.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnPredict.setText("ทำนาย");
        btnPredict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPredictActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ทำนายดวงความรักตามวันเกิด");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("นิสัย");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("วันเกิด");

        rdlMonday.setBackground(new java.awt.Color(255, 51, 102));
        buttonGroup1.add(rdlMonday);
        rdlMonday.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdlMonday.setForeground(new java.awt.Color(255, 255, 255));
        rdlMonday.setText("วันจันทร์");
        rdlMonday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdlMondayActionPerformed(evt);
            }
        });

        tarCharacter.setColumns(20);
        tarCharacter.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        tarCharacter.setRows(5);
        jScrollPane1.setViewportView(tarCharacter);

        rdlTuesday.setBackground(new java.awt.Color(255, 51, 102));
        buttonGroup1.add(rdlTuesday);
        rdlTuesday.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdlTuesday.setForeground(new java.awt.Color(255, 255, 255));
        rdlTuesday.setText("วันอังคาร");
        rdlTuesday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdlTuesdayActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("นิสัยเวลามีความรัก");

        tarCharcterlove.setColumns(20);
        tarCharcterlove.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        tarCharcterlove.setRows(5);
        jScrollPane2.setViewportView(tarCharcterlove);

        rdlSaturday.setBackground(new java.awt.Color(255, 51, 102));
        buttonGroup1.add(rdlSaturday);
        rdlSaturday.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdlSaturday.setForeground(new java.awt.Color(255, 255, 255));
        rdlSaturday.setText("วันเสาร์");
        rdlSaturday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdlSaturdayActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Viner Hand ITC", 1, 23)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        rdlWednesday.setBackground(new java.awt.Color(255, 51, 102));
        buttonGroup1.add(rdlWednesday);
        rdlWednesday.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdlWednesday.setForeground(new java.awt.Color(255, 255, 255));
        rdlWednesday.setText("วันพุทธ");
        rdlWednesday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdlWednesdayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPredict)
                .addGap(139, 139, 139))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(44, 44, 44)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rdlMonday)
                                            .addComponent(rdlThursday)
                                            .addComponent(rdlSunday)))
                                    .addComponent(jLabel3))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdlTuesday)
                                    .addComponent(rdlFriday))
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rdlWednesday)
                                    .addComponent(rdlSaturday)))
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(41, 41, 41)
                                .addComponent(lblPersen, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel1)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rdlMonday)
                    .addComponent(rdlTuesday)
                    .addComponent(rdlWednesday))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdlThursday)
                    .addComponent(rdlFriday)
                    .addComponent(rdlSaturday))
                .addGap(18, 18, 18)
                .addComponent(rdlSunday)
                .addGap(17, 17, 17)
                .addComponent(btnPredict)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addContainerGap(116, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPersen, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void rdlMondayActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void rdlTuesdayActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void rdlWednesdayActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void rdlThursdayActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void rdlFridayActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void rdlSaturdayActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void rdlSundayActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void btnPredictActionPerformed(java.awt.event.ActionEvent evt) {                                           
        if (rdlMonday.isSelected()) {
            tarCharacter.setText("ปกติคนที่เกิดวันนี้เป็นคนที่ค่อนข้างแพรวพราว เป็นคนที่ค่อนข้างจะรักอิสระ ดู\n" +
"เป็นคนเจ้าชู้ไม่รู้ตัว เพราะเป็นคนมีเสน่ห์ วางตัวดี");
            tarCharcterlove.setText("ถ้ามีความรักขึ้นมาล่ะก็ เหมือนเป็นคนละคน! จากเสีอตัวใหญ่ พอ\n" +
"มีแฟนแล้วจะกลายเป็นแมวน้อย ขี้อ้อน เอาใจ อยากได้อะไรจัดให้ทุกอย่าง งอแงกับแฟนเพราะอยากเรียกร้อง\n" +
"ความสนใจ ถ้าคบกันแล้วก็อยากให้ดูแล เอาอกเอาใจซึ่งกันและกัน มือถือนี่ถ้าไม่ล็อกรหัสก็เรียบร้อย! เพราะ\n" +
"คนเกิดวันนี้จะแอบหึง แอบส่องทุกอย่าง แฟนไปไหน ทําอะไร อยู่กับใคร รู้หมด! แต่ คนที่เกิดวันจันทร์ถึงจะมี\n" +
"แฟนยังไงก็ยังไม่ทิ้งเพื่อน ถ้าอีกฝ่ายเข้าใจ ไม่คิดมากก็คบกันได้ยาว ๆ จ้า");
            lblPersen.setText("100%");
        } else if (rdlTuesday.isSelected()) {
             tarCharacter.setText("คนเกิดวันนี้เป็นพ่อแม่บุญทุ่ม เวลารักใครจะจริงจังมากระดับสิบ! เป็นคนใจร้อน\n" +
"ตอบช้า 5 นาทีจะรู้สึกใจหายแล้ว ว่าเราพูดอะไรผิดไปไหมนะ? หรือว่าเขาไม่อยากคุยกับเราหรือเปล่า? หรือว่า\n" +
"เกิดเหตุร้ายอะไรขึ้น เอ๊ะ! หรือว่าแอบคุยกับคนอื่น");
             tarCharcterlove.setText("ถ้าอยู่ในช่วงอินเลิฟแล้วจะอารมณ์ดีทั้งวัน ยิ้มคนเดียว เป็นคนติด\n" +
"แฟน อยากอยู่ด้วยตลอดเวลา เธออยู่ที่ไหน จะไปอยู่ตรงหน้า จะไปหาแน่ ๆ! และค่อนข้างคาดหวังในตัวคนรัก\n" +
"มาก ๆ ถ้าให้ 100 ต้องได้กลับมา 100 ชอบอะไรที่แฟร์ ๆ ถ้าไม่แฟร์ก็หาใหม่ ชอบความตื่นเต้นท้าทาย ถ้าอีก\n" +
"ฝ่ายเล่นตัวนิดหน่อย เข้าหาบ้าง เอาใจก่อนบ้าง แกล้งไม่ตอบบ้าง ยิ่งตื่นเต้น ยิ่งถ้าอีกฝ่ายใส่ใจ และเข้าใจใน\n" +
"ตัวของคนที่เกิดวันอังคาร รับรองว่ารักจนมูฟออนไปไหนไม่ได้!");
             lblPersen.setText("80%");
        } else if (rdlWednesday.isSelected()) {
            tarCharacter.setText("คารมดีเป็นที่ 1 ตบมุขโบ๊ะบ๊ะได้ ทันคน เทคนิคอ่อยชั้นครู แพรวพราวพอ ๆ กับคน\n" +
"เกิดวันจันทร์ เป็นคนที่ค่อย ๆ ดู ค่อย ๆ เก็บข้อมูลฝ่ายตรงข้าม ไม่วู่วาม ชอบนะ แต่ไม่แสดงออกตรง ๆ รอ\n" +
"จนกว่าจะแน่ใจจริง ๆ แล้วถึงจะตกลงเป็นแฟน");
             tarCharcterlove.setText("เป็นคนที่รักใครแล้วรักจริง โรแมนติก เรื่องเล็ก ๆ น้อยก็จําได้ เอาใจ\n" +
"ใส่แฟนหรือคนรักมาก แต่ข้อเสียของคนที่เกิดวันนี้ เป็นเพราะอีโก้ที่สูงเสียดฟ้า อาจจะทําให้เรื่องราวที่มันไม่ได้\n" +
"มีอะไรเลย พังได้ง่าย ๆ เพราะความมีอีโก้ของตัวเอง เวลาโกรธมาก็จะใช้คําพูดที่ไม่ค่อยดี เป็นคนคาดหวังกับ\n" +
"ความรักสูง คิดมาก ขี้หึง ขี้ระแวง แล้วพอไม่ได้ตามที่หวัง ก็อาจจะพาลเบื่อได้ง่าย ๆ แนะนําให้ใจเย็น ๆ และ\n" +
"ลดความคาดหวังกับอีโก้ลงนิดหน่อย จะทําให้ความรักไปได้ดี");
             lblPersen.setText("50%");
        } else if (rdlThursday.isSelected()){
            tarCharacter.setText("ภายนอกอาจจะดูเป็นคนอ่อยเก่ง แพรวพราว แต่จริง ๆ แล้วเป็นคนค่อนข้าง\n" +
"อ่อนไหว เป็นคนออกจะบ๊อง ๆ ขาด ๆ เกิน ๆ ด้วยซ้ํา คนเกิดวันนี้ถึงจะดูอ่อยเก่งก็จริง ดูเป็นสาวฮอต หนุ่ม\n" +
"ฮอต แต่รักใครแล้วรักจริงจังมาก ไม่ชอบการนอกใจ และการถูกหักหลัง");
            tarCharcterlove.setText("เวลาคนเกิดวันพฤหัสบดีมีความรักแล้วเหมือนเมากัญชา อารมณ์\n" +
"ดีทั้งวัน และวันครบรอบ วันเกิด จําได้หมด ตกหลุมรักคนง่าย ยิ่งถ้าเจอคนที่คุยแบบ Deep Conversation\n" +
"ได้ ยิ่งชอบ ชอบคนที่เป็นผู้ใหญ่ ยิ่งมีทัศนคติดี ๆ หรือพลังบวก คนที่เกิดวันพฤหัสบดีจะมโนไปถึงขั้นแต่งงาน\n" +
"เลย ทั้ง ๆ ที่แค่เริ่มคุย แต่ก็ชอบความรักที่ค่อยเป็นค่อยไป ไม่รีบนะ");
             lblPersen.setText("60%");
       } else if (rdlFriday.isSelected()){
           tarCharacter.setText("คนเกิดวันนี้ออกแนวพ่อบ้านใจกล้า ไม่เถียงหรอกนะ แต่อย่าให้โกรธ! เป็นคนช่าง\n" +
"มโน ชอบเพ้อเงียบ ๆ เป็นตุเป็นตะอยู่คนเดียว และคนเกิดวันนี้เป็นคนอ่อนโยน เอาใจใส่แฟนมาก ต้องการให้\n" +
"\n" +
"แฟนเอาใจใส่ตัวเองเหมือนกัน ถ้าเจอคนที่ทําให้คนเกิดวันศุกร์รู้สึกรักทั้งแฟน รักทั้งตัวเอง หรือชอบตัวเองตอน\n" +
"อยู่กับแฟน จะเป็นอะไรที่เพอร์เฟ็กต์มาก");
            tarCharcterlove.setText(": ใครชอบคนสายเปย์ มาทางนี้! คนเกิดวันศุกร์บอกเลยว่าเปย์เก่งงงง\n" +
"ชอบหาอะไรทํา ชวนแฟนทํานู่น ทํานี่ อยู่ด้วยแล้วไม่มีทางเบื่อแน่นอน และมักจะเจอคนที่แตกต่างกันที่ อายุ\n" +
"เชื้อชาติ ศาสนา ฐานะ ฯลฯ แต่ไม่ค่อยสนใจเท่าไร ถ้าพร้อมจะเดินไปด้วยกันก็โอเค คบกันได้ยาว ๆ");
            lblPersen.setText("85%");
       } else if (rdlSaturday.isSelected()){
            tarCharacter.setText("คนที่เกิดวันเสาร์ชอบทําตัวเป็นผู้นํา อีโก้สูง บ้าพลัง ไม่ชอบคนต่อล้อต่อเถียง ฉะนั้น\n" +
"คนที่นิ่ง ๆ สุขุมหน่อย ๆ ก็จะเข้าทางคนที่เกิดวันนี้ เป็นคนเด็ดขาด ชัดเจน ชอบก็คือชอบ ไม่ยึก ๆ ยัก ๆ ชอบ\n" +
"คนเอาใจ ใส่ใจ ชอบอะไรที่เรียบง่าย มั่นคง ถ้ามีแฟนแล้วก็จะทุ่มสุด ๆ");
            tarCharcterlove.setText("อยากได้อะไรบอกจะจัดให้ตามที่ขอทุกอย่าง ยกเว้นให้ลุงลาออก\n" +
"(เอ๊ย! ไม่ใช่!) ดูแลแฟนหรือคนรักดีเว่อร์! เหมือนเราเป็นเจ้าหญิงหรือเจ้าชาย แต่ไม่ชอบอะไรที่จุกจิก ชนิดว่า\n" +
"ตามหึงตามจิกเกินเบอร์จะเบื่อมาก แต่ถึงจะไม่ชอบอะไรแบบนั้น คนที่เกิดวันเสาร์เวลาหึงจะน่ากลัวระดับสิบ!");
            lblPersen.setText("70%");
       } else if (rdlSunday.isSelected()){
           tarCharacter.setText("คนที่เกิดวันอาทิตย์ เขาว่าเป็นคนอารมณ์ขึ้น ๆ ลง ๆ อาจจะตามอารมณ์ยากสัก\n" +
"หน่อย เป็นคนใจกว้าง ให้อิสระกับคนรัก แต่ถ้าเข้าโหมดจริงจังแล้วไม่ชอบอะไรเล่น ๆ อยู่ไหน ทําอะไรกับใคร\n" +
"ต้องบอก ต้องรายงาน และถ้าชอบใครก็จะทําทุกวิถีทางเพื่อให้ได้คบ");
           tarCharcterlove.setText("พอมีแฟนแล้วโลกสดใส อะไรก็เป็นสีชมพูไปหมด ถ้ามีแฟนจะขี้\n" +
"บ่นมาก ๆ แต่ก็เป็นเพราะรักแหละถึงบ่น เป็นคนรักเดียวใจเดียว คบใครก็คบทีละคน ไม่ได้หว่านไปทั่วถ้าเทียบ\n" +
"กับคนเกิดวันอื่น ๆ ถ้าเจอแฟนหรือคนรักที่เข้ากับครอบครัวหรือเพื่อนได้ก็ผ่านฉลุย เพราะชอบความรักแบบ\n" +
"ลึกซึ้ง พร้อมที่จะเป็นครอบครัวเดียวกันในอนาคต ชอบคนพูดเพราะ ใส่ใจ ยิ้มหวาน ถ้าสอบผ่านก็จะเสมอต้น\n" +
"เสมอปลายกับคนรักมาก ๆ");
            lblPersen.setText("75%");
       }
    }                                          

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {                                        
       int option = JOptionPane.showConfirmDialog(rootPane, "Exit");
        if(option == JOptionPane.YES_OPTION);
        System.exit(0);
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fortune_Telling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fortune_Telling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fortune_Telling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fortune_Telling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fortune_Telling().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPredict;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPersen;
    private javax.swing.JRadioButton rdlFriday;
    private javax.swing.JRadioButton rdlMonday;
    private javax.swing.JRadioButton rdlSaturday;
    private javax.swing.JRadioButton rdlSunday;
    private javax.swing.JRadioButton rdlThursday;
    private javax.swing.JRadioButton rdlTuesday;
    private javax.swing.JRadioButton rdlWednesday;
    private javax.swing.JTextArea tarCharacter;
    private javax.swing.JTextArea tarCharcterlove;
    // End of variables declaration                   
}
